## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# Workflow:
#
# First start by watching the changes in nix with the watcher
# ```bahs
# fzz -t nix
# ```
# Proceed to make the changes in the .dotfiles

- name: validate sway
  run: 'nix/nixos/sway/validate.sh'
  change: 'nix/nixos/sway/**'

# Usage: `fzz -t nix`
- name: watch nix configs
  run: 
    - nix flake check nix
    - nix/rebuild.sh
  change: 'nix/**'
  run_on_init: true

- name: watch osx keyboard mappings
  run: 'killall skhd' # Force restart service
  change: 'nix/osx/yabai/**'
