## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# Workflow:
#
# First start by watching the changes in nix with the watcher
# ```bahs
# fzz -t nix
# ```
# Proceed to make the changes in the .dotfiles
#
- name: adds to git
  run_on_init: true
  run:
    - git add {{relative_filepath}}
    - git add -p
  change: 
    - .fzz/git-task # touch .fzz/git-task
    - '**/*' ## FIXME fzz issue with non strings
  ignore:
    - '.git/**/*'
    - result

- name: validate sway
  run: 'nix/nixos/sway/validate.sh'
  change: 'nix/nixos/sway/**'

# Usage: `fzz -t nix`
- name: watch nix configs
  run: 
    # linter
    - statix check -i nix/nixos/hardware-configuration.nix
    # FIXME it fails on osx
    # - nix flake check nix --no-build
    - nix/rebuild.sh
  change: 
    - 'nix/**/*.nix'
  run_on_init: true

- name: watch osx keyboard mappings
  run: 'killall skhd' # Force restart service
  change: 'nix/osx/yabai/**'
    
- name: after commit attempt to rebase
  run: 
    - git fetch --all
    - git rebase origin/master
  change: 
    - ".git/COMMIT_EDITMSG"
