## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: watch nix configs
  run: 'nix/rebuild.sh'
  change: 'nix/**'
  run_on_init: true
